name: "[PART] Unit tests"
on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Fazer checkout
      
      - name: 'Usar node.js v18'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run test

      - name: 'Upload coverage'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./coverage