name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build: 
    uses: ./.github/workflows/_build.yml

  unit-tests:
    uses: ./.github/workflows/_unit-tests.yml