name: Build and test
on:
  push:
    branches: [main]
  release:
    types:
      - created
      - edited

jobs:
  build: 
    uses: ./.github/workflows/_build.yml

  unit-tests:
    uses: ./.github/workflows/_unit-tests.yml